"""Build the dashboard's data files from the committed model results.

    dashboard/src/data/aiScenarios.json   indices, labour share, growth, US endpoints
    dashboard/src/data/ukAiPaths.json     the 2000-2029 chart: OBR history + scenario paths

Inputs, all in ``data/``:

``scenarios.json``          model results (``python -m uk_growth_with_ai run``)
``og_uk_params.json``       trend parameters used to re-trend detrended output
``obr_history.json``        OBR outturn/forecast lines and chart panel layout
``anthropic_us_2030.json``  Anthropic's published US 2030 endpoints

``python -m uk_growth_with_ai dashboard`` writes both files; ``--check`` fails if
the committed files differ from what the results produce.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from .data_access import DATA, load_results, load_trend_params
from .report import growth_path, labour_share, trend

DASHBOARD_DATA = Path(__file__).resolve().parent.parent / "dashboard" / "src" / "data"

YEARS = [2026, 2027, 2028, 2029, 2030]
ARMS = ["baseline", "obr_ramp", "anthropic_ramp"]
VARS = [["C", "Consumption"], ["I", "Investment"], ["G", "Government"],
        ["total_tax_revenue", "Tax revenue"], ["D", "Debt"], ["Y", "GDP"],
        ["w", "Average wage"], ["K", "Capital stock"], ["L", "Labour"]]

# The 2000-2029 chart shows the scenario paths to 2029 only (issue #3).
PATH_YEARS = YEARS[:4]
ARM_TRACE = {
    "baseline": ("UK, no AI", "#5a6470"),
    "obr_ramp": ("UK, OBR displacement", "#2f6fb5"),
    "anthropic_ramp": ("UK, Anthropic substantial", "#1d7a4c"),
}

DERIVATION = (
    "Indexed to the 2026 baseline = 100: detrended OG-UK levels re-trended as "
    "OG-Core detrends them (e^{g_y t} for productivity, N_t for population; the "
    "wage carries productivity only, labour population only), using the g_y and "
    "g_n the run recorded, then divided by the baseline 2026 level. Generated by "
    "uk_growth_with_ai.dashboard_data from data/scenarios.json."
)


def _read(name: str) -> dict:
    return json.loads((DATA / name).read_text())


def ai_scenarios(results=None, oguk_dir=None) -> dict:
    res = results if results is not None else load_results()
    g_n, g_y = load_trend_params(oguk_dir, res)
    idx = {
        arm: {v: list(np.array(res[arm][v][:5]) * trend(v, g_y, g_n)
                      / res["baseline"][v][0] * 100)
              for v, _ in VARS}
        for arm in ARMS
    }
    return {
        "years": YEARS,
        "arms": ARMS,
        "vars": VARS,
        "idx": idx,
        "sl": {arm: list(labour_share(res[arm])) for arm in ARMS},
        "grow": {arm: list(growth_path(res[arm]["Y"], g_y, g_n)) for arm in ARMS},
        "anth": _read("anthropic_us_2030.json")["scenarios"],
        "assum": res["assumptions"],
        "derivation": DERIVATION,
    }


def uk_paths(results=None, ai=None) -> dict:
    """Scenario paths rebased to the OBR line at 2026.

    GDP: OBR 2026 level times the scenario's GDP index / 100. Ratios: OBR 2026
    value times the scenario's model ratio over the baseline's 2026 model ratio,
    so the paths start at the OBR's level and move at the model's rate.
    """
    res = results if results is not None else load_results()
    ai = ai if ai is not None else ai_scenarios(res)
    panels = []
    for p in _read("obr_history.json")["panels"]:
        v, obr = p["var"], p["obr"]
        o26 = dict(zip(obr["x"], obr["y"]))[2026]
        traces = [obr]
        for arm in ARMS:
            if v == "Y":
                y = [o26 * x / 100 for x in ai["idx"][arm]["Y"][:4]]
            else:
                b0 = res["baseline"][v][0] / res["baseline"]["Y"][0]
                y = [o26 * (res[arm][v][i] / res[arm]["Y"][i]) / b0 for i in range(4)]
            name, color = ARM_TRACE[arm]
            traces.append({
                "name": name, "x": PATH_YEARS, "y": [round(x, 3) for x in y],
                "color": color, "width": 2.4, "dash": "solid",
                "hovertemplate": f"%{{x}}: %{{y:.2f}}<extra>{name}</extra>",
                "legendgroup": name, "showlegend": True,
            })
        panels.append({"title": p["title"], "traces": traces, "shapes": p["shapes"],
                       "yRangeMode": p["yRangeMode"]})
    return {"panels": panels}


def _dump(obj) -> str:
    return json.dumps(obj, indent=1)


def build(results=None, oguk_dir=None) -> dict[str, str]:
    """File name -> JSON text, exactly as committed."""
    res = results if results is not None else load_results()
    ai = ai_scenarios(res, oguk_dir)
    return {"aiScenarios.json": _dump(ai), "ukAiPaths.json": _dump(uk_paths(res, ai))}


def write(out_dir=DASHBOARD_DATA, results=None, oguk_dir=None) -> list[Path]:
    out = Path(out_dir)
    paths = []
    for name, text in build(results, oguk_dir).items():
        (out / name).write_text(text)
        paths.append(out / name)
    return paths


def stale(out_dir=DASHBOARD_DATA, results=None, oguk_dir=None) -> list[str]:
    """Names of dashboard files that differ from what the results produce."""
    out = Path(out_dir)
    return [name for name, text in build(results, oguk_dir).items()
            if not (out / name).exists() or (out / name).read_text() != text]
